### ISSUE TITLE
NotImplementedError - can't connect to Facebook?

### ISSUE THREAD

**Issue by pniewiadowski** [yshalsager/facebook2rss#16] opened 2021-02-22 21:07 UTC
Don't know if I am doing something wrong, or I found some issue, so I would appreciate some help.
I run this:
`py -m facebook_rss --login --email "mail@mail.com" --password "secret_password"`

And then this:
`uvicorn.exe facebook_rss.main:api --port 8080`

Went to http://localhost:8080/docs to put facebook group ID
![image](https://user-images.githubusercontent.com/28837813/108770051-27319780-755a-11eb-8905-5178c1399fcc.png)

and click execute and that shows up in uvicorn log:
```
2021-02-22 22:02:11,131 [INFO] uvicorn.error [server.serve:64]: Started server process [7396]
2021-02-22 22:02:11,132 [INFO] uvicorn.error [on.startup:26]: Waiting for application startup.
2021-02-22 22:02:11,132 [INFO] fastapi [main.startup_event:44]: Performing startup tasks...
2021-02-22 22:02:11,133 [INFO] fastapi [main.startup_event:50]: Login cookies file was found, setting working mode to use account!
2021-02-22 22:02:11,133 [INFO] uvicorn.error [on.startup:38]: Application startup complete.
2021-02-22 22:02:11,133 [INFO] uvicorn.error [server._log_started_message:199]: Uvicorn running on http://127.0.0.1:8080 (Press CTRL+C to quit)
2021-02-22 22:02:27,854 [ERROR] asyncio [base_events.default_exception_handler:1707]: Task exception was never retrieved
future: <Task finished name='Task-6' coro=<Connection.run() done, defined at C:\Users\Przemek\AppData\Roaming\Python\Python38\site-packages\playwright\_impl\_connection.py:136> exception=NotImplementedError()>
Traceback (most recent call last):
  File "C:\Users\Przemek\AppData\Roaming\Python\Python38\site-packages\playwright\_impl\_connection.py", line 139, in run
    await self._transport.run()
  File "C:\Users\Przemek\AppData\Roaming\Python\Python38\site-packages\playwright\_impl\_transport.py", line 56, in run
    proc = await asyncio.create_subprocess_exec(
  File "c:\program files\python38\lib\asyncio\subprocess.py", line 236, in create_subprocess_exec
    transport, protocol = await loop.subprocess_exec(
  File "c:\program files\python38\lib\asyncio\base_events.py", line 1630, in subprocess_exec
    transport = await self._make_subprocess_transport(
  File "c:\program files\python38\lib\asyncio\base_events.py", line 491, in _make_subprocess_transport
    raise NotImplementedError
NotImplementedError
```

What next I can do to help to resolve this?

**Comment by yshalsager** [comment] 2021-02-23 08:23
Duplicate of https://github.com/yshalsager/facebook2rss/issues/11

Please use docker on windows for now.

**Closed as completed** 2021-02-23 08:23 UTC
